CREATE TABLE IF NOT EXISTS `b_awz_currency` (
`ID` int(18) NOT NULL AUTO_INCREMENT,
`CODE` varchar(3) NOT NULL,
`PROVIDER` varchar(25) NOT NULL,
`AMOUNT` decimal(10,4) NOT NULL,
`AMOUNT_CNT` int(9) NOT NULL,
`CURS_DATE` datetime NOT NULL,
PRIMARY KEY (`ID`),
unique IX_CURS_DATE_CODE_PROVIDER (PROVIDER, CODE, CURS_DATE)
);